name = "tg-image"
compatibility_date = "2023-01-01"
main = "src/index.js"

[vars]
# 可以在这里设置默认环境变量
# TG_Bot_Token = "8116484812:AAHIfsz9iFiMwWi2_BwQ1kuUrRWQgkCcdRw"
# TG_Chat_ID = "-1002509744447"
JWT_SECRET = "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.JkKWCY39IdWEQttmdqR7VdsvT-_QxheW_eb0S5wr_j83ltux_JDUIXs7a3Dtn3xuqzuhetiuJrWIvy5TzimeCg"

# 注意：在部署前，请先创建这些 KV 命名空间，并将生成的 ID 填入下面的配置中
# 使用以下命令创建 KV 命名空间（Wrangler 4.x 版本）：
# npx wrangler kv namespace create "img_url"
# npx wrangler kv namespace create "users"
#
# 或者使用 npm run create-kv 命令自动创建 KV 命名空间并更新配置

[[kv_namespaces]]
binding = "img_url"
id = "a5efe765919840279060c72a15082608"

[[kv_namespaces]]
binding = "users"
id = "a5efe765919840279060c72a15082608"

[site]
bucket = "./public"
